import { StyleSheet, Dimensions } from 'react-native'
import { Constants } from 'expo';

const PAGE_WIDTH = Dimensions.get('window').width;

const styles = StyleSheet.create({
  inputField: {
    alignSelf: 'stretch',
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 10,
    paddingLeft: 10,
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 5,
    height: 60,
    // borderColor: 'gray',
    borderWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.9)'
  },
  inputField2: {
    alignSelf: 'stretch',
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 10,
    paddingLeft: 10,
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 5,
    height: 50,
    // borderColor: 'gray',
    borderWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.9)'
  },
  inputField3: {
    alignSelf: 'stretch',
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 10,
    paddingLeft: 10,
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 5,
    height: 90,
    // borderColor: 'gray',
    borderWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.9)'
  },
  inputField4: {
    alignSelf: 'stretch',
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 10,
    paddingLeft: 10,
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 5,
    height: 50,
    // borderColor: 'gray',
    borderWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    width: 90
  },
  buttonLabel: {
    textAlign: 'center',
    fontSize: 16,
    color: 'white',
    fontWeight: 'bold',
  },
  buttonLabel2: {
    textAlign: 'center',
    fontSize: 16,
    color: 'blue',
    fontWeight: 'bold',
  },
  button: {
    alignSelf: 'stretch',
    paddingTop: 10,
    paddingBottom: 10,
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 5,
  },
  buttonLightBlue: {
    backgroundColor: '#CB3066'
  },
    container5: {
      flexDirection: 'column',
      backgroundColor: 'red',
      borderColor: '#2448a2',
      borderWidth: 2,
      flex: 1,
      height: 100,
      width: 375,
    },
    mapHalf: {
      flex:3,
      flexDirection: 'row',
      backgroundColor: 'yellow',
    },
    bottomHalf: {
      backgroundColor: 'pink',
      borderWidth: 2,
      borderColor: '#2448a2',
      width: 375,
      height: 50,
      flex:1,
    },
    map: {
      flex: 1,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    buttonContainer: {
      marginVertical: 20,
      backgroundColor: 'maroon',
      flex:1,
    },
    button5: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.75)',
      borderRadius: 20,
      padding: 10,
      width: 100,
      height: 40,
      marginVertical: 20,
      borderColor:'#2448A2',
      borderWidth: 1,
      flex:1,
    },
    buttonText5: {
      alignItems:'center',
    },
    timeSliderView: {
      flex: 1,
      height: 100,
      width: 375,
      alignItems: 'center',
      justifyContent: 'flex-start',
      flexDirection: 'row',
      backgroundColor: '#4C69B0',
    },
    paceSliderView: {
      flex: 1,
      backgroundColor:'purple',
      height: 100,
      width: 375,
      alignItems: 'center',
      flexDirection: 'row',
      backgroundColor: '#4C69B0',
    },
    slider: {
      width: 100,
      height: 30,
      backgroundColor:'#4C69B0',
      flex:4,
    },
    textTime: {
      backgroundColor: '#4C69B0',
      color: 'white',
      flex: 1
    },
    textPace: {
      backgroundColor: '#4C69B0',
      color: 'white',
      flex: 1
    },
    container3: {
      backgroundColor: '#4C69B0',
      flex: 1,
      flexDirection: 'column',
      color: 'white',
      width: '100%',
      overflow: 'scroll',
      paddingTop: 40,
      paddingBottom: 40,
    },
    cont: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    item: {
      alignSelf: "flex-start",
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
      maxHeight: 30,
      maxWidth: 30
    },
    itemText: {
      fontSize: 20
    },
    shadow: {
      elevation: 16,
      shadowColor: '#000000',
      shadowOpacity: 0.5,
      shadowRadius: 20,
      shadowOffset: {
        height: 12
      }
    },
    container: {
      flex: 1,
    },
    container1: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#4C68B1',
    },
    title: {
      fontSize: PAGE_WIDTH / 12,
      fontWeight: 'bold',
      color: '#fff',
      backgroundColor: 'transparent',
      textAlign: 'center'
    },
    desc: {
      fontSize: PAGE_WIDTH / 24,
      color: '#fff',
      backgroundColor: 'transparent',
      marginTop: 20,
      lineHeight: 25,
      textAlign: 'center'
    },
    page: {
      width: PAGE_WIDTH,
      paddingTop: Constants.statusBarHeight + 48,
    },
    card: {
      position: 'absolute',
      margin: 12,
      marginTop: 40,
      left: 12,
      top: 0,
      right: 0,
      borderRadius: 8,
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 140,
    },
    frame: {
      position: 'absolute',
      left: 0,
      bottom: 160,
      borderRadius: (PAGE_WIDTH -100)/2,
      height: PAGE_WIDTH -100,
      width: PAGE_WIDTH - 100,
      margin: 50,
    },
    buttonRegister: {
      backgroundColor: 'rgba(0,0,0, 0.3)',
      position: 'absolute',
      margin: 12,
      marginLeft: -60,
      marginTop: 40,
      left: (PAGE_WIDTH / 2) - 100,
      borderRadius: 50,
      alignItems: 'center',
      bottom: 30,
    },
    buttonRegister1: {
      backgroundColor: 'rgba(0,0,0, 0.3)',
      position: 'absolute',
      margin: 12,
      marginLeft: 20,
      marginTop: 40,
      left: (PAGE_WIDTH / 2) - 100,
      borderRadius: 50,
      alignItems: 'center',
      bottom: 30,
    },
    buttonLogin: {
      backgroundColor: 'rgba(0,0,0, 0.3)',
      position: 'absolute',
      margin: 12,
      marginLeft: 115,
      marginTop: 40,
      left: (PAGE_WIDTH / 2) - 100,
      borderRadius: 50,
      alignItems: 'center',
      bottom: 30,
    },
    buttonLogin1: {
      backgroundColor: 'rgba(0,0,0, 0.3)',
      position: 'absolute',
      margin: 12,
      marginLeft: 35,
      marginTop: 40,
      left: (PAGE_WIDTH / 2) - 100,
      borderRadius: 50,
      alignItems: 'center',
      bottom: 30,
    },
    buttonText: {
      margin: 15,
      marginLeft: 50,
      marginRight: 40,
      color: '#fff',
      fontSize: 14,
    },
    photo: {
      flex: 1,
      borderRadius: (PAGE_WIDTH -100)/2,
    }
  });

  module.exports = styles;